breed_to_type = {
    'Pit Bull': 'Pit Bull Type',
    'American Staffordshire Terrier': 'Pit Bull Type',
    'Pit Bull Cross': 'Pit Bull Type',
    'Bullmastiff X Pit Bull': 'Pit Bull Type',
    'Pit Bull - Pit Monster': 'Pit Bull Type',
    'Pit Bull Mix': 'Pit Bull Type',
    'American Pit Bull Terrier': 'Pit Bull Type',
    'Pit Bull Type': 'Pit Bull Type',
    'Pitbull Cross X Staffordshire': 'Pit Bull Type',
    'American Bully': 'Pit Bull Type',
    'American Bully X American Staffordshire Terrier': 'Pit Bull Type',
    'American Bully Xl': 'Pit Bull Type',
    'Pit Bull Terrier Mix': 'Pit Bull Type',
    'Pit Bull X Staffordshire Bull Terrier Cross': 'Pit Bull Type',
    'American Staffordshire Terrier Cross': 'Pit Bull Type',
    'American Staffordshire Terrier X Rottweiler': 'Pit Bull Type',
    'American Staffordshire Terrier X Dogo Argentino': 'Miscellaneous',
    'American Bully Xl X Cane Corso': 'Miscellaneous',
    'Bullmastiff': 'Mastiff Type',
    'Bullmastiff Cross': 'Mastiff Type',
    'Mastiff Cross': 'Mastiff Type',
    'Neapolitan Mastiff': 'Mastiff Type',
    'German Mastiff': 'Mastiff Type',
    'Spanish Mastiff': 'Mastiff Type',
    'English Mastiff': 'Mastiff Type',
    'Mastiff X Pit Bull Mix': 'Mastiff Type',
    'Mastiff X Staffordshire Bull Terrier': 'Miscellaneous',
    'Bullmastiff X Pit Bull': 'Mastiff Type',
    'Bull Mastiff X Presa Canario': 'Mastiff Type',
    'Mastiff Or Bullmastiff': 'Mastiff Type',
    'German Mastiff X Saint Bernard Mix': 'Miscellaneous',
    'German Mastiff X Mastiff Mix': 'Mastiff Type',
    'Bulldog Mix X Mastiff': 'Miscellaneous',
    'Bloodhound X Mastiff': 'Mastiff Type',
    'German Shepherd': 'Shepherd Type',
    'German Shepherd Cross': 'Shepherd Type',
    'German Shepherd X Labrador Retriever': 'Shepherd Type',
    'German Shepherd X Rottweiler': 'Shepherd Type',
    'German Shepherd X Husky': 'Miscellaneous',
    'German Shepherd X Husky Cross': 'Miscellaneous',
    'Coyote X German Shepherd': 'Shepherd Type',
    'Beauceron X German Shepherd X Rottweiler Mix': 'Miscellaneous',
    'Chow Chow X German Shepherd Cross': 'Miscellaneous',
    'German Shepherd Mix X Labrador': 'Miscellaneous',
    'German Shepherd Mix X Rottweiler': 'Miscellaneous',
    'Belgian Shepherd - Malinois': 'Shepherd Type',
    'Caucasian Shepherd Dog': 'Shepherd Type',
    'American Bulldog': 'Bulldog Type',
    'Bulldog': 'Bulldog Type',
    'Bulldog Type': 'Bulldog Type',
    'Bordeaux Bulldog': 'Bulldog Type',
    'British Bulldog': 'Bulldog Type',
    'Olde Bulldogge': 'Bulldog Type',
    'Alapaha Blue Blood Bulldog': 'Bulldog Type',
    'Bulldog Cross': 'Bulldog Type',
    'Bulldog Mix': 'Bulldog Type',
    'American Bulldog X Bull Terrier Cross Or English Bull Terrier': 'Miscellaneous',
    'American Bulldog Or Pitbull X Husky': 'Miscellaneous',
    'American Bulldog X Great Pyrenees Mix': 'Miscellaneous',
    'French Bulldog Mix': 'Bulldog Type',
    'Rottweiler': 'Rottweiler Type',
    'Rottweiler Mix': 'Rottweiler Type',
    'Dobermann': 'Pinscher Type',
    'Doberman': 'Pinscher Type',
    'Bandog Bullmastiff Cross': 'Mastiff Type',
    'Cane Corso': 'Mastiff Type',
    'Dogo Argentino': 'Mastiff Type',
    'Kangal': 'Shepherd Type',
    'Boerboel': 'Mastiff Type',
    'Boerboel Cross': 'Mastiff Type',
    'Czechoslovakian Wolfdog': 'Miscellaneous',
    'Saint Bernard': 'Saint Bernard',
    'Leonese Sheepdog': 'Leonese Sheepdog',
    'Fila Brasileiro': 'Mastiff Type',
    'Fila Mix X Shar-Pei': 'Miscellaneous',
    'Husky': 'Husky Type',
    'Husky Cross': 'Husky Type',
    'Alaskan Malamute': 'Husky Type',
    'Alaskan Malamute X Husky': 'Husky Type',
    'Siberian Husky': 'Husky Type',
    'Husky X Wolf Cross': 'Husky Type',
    'Canadian Eskimo Dog': 'Husky Type',
    'Greenland Dog': 'Husky Type',
    'Sled Dog': 'Husky Type',
    'Staffordshire Bull Terrier': 'Pit Bull Type',
    'Bull Terrier': 'Terrier Type',
    'Staffordshire Bull Terrier Cross': 'Pit Bull Type',
    'Lakeland Terrier Cross': 'Terrier Type',
    'Jack Russell Terrier': 'Terrier Type',
    'Terrier Mix': 'Terrier Type',
    'Golden Retriever': 'Retriever Type',
    'Labrador': 'Retriever Type',
    'Labrador Mix': 'Retriever Type',
    'Labrador Retriever Mix': 'Retriever Type',
    'Cattle Dog': 'Herding Type',
    'Border Collie': 'Herding Type',
    'Collie': 'Herding Type',
    'Maremmano-Abruzzese Sheepdog': 'Herding Type',
    'Stray Dog': 'Miscellaneous',
    'Unknown': 'Miscellaneous',
    'Mixed Breed': 'Miscellaneous',
    'Chow Chow': 'Miscellaneous',
    'Newfoundland': 'Miscellaneous',
    'Poodle': 'Miscellaneous',
    'Bird Dog': 'Miscellaneous',
    'Beagle': 'Miscellaneous',
    'Wolfdog Hybrid': 'Miscellaneous',
    'Corgie Mix X Sheltland Sheepdog': 'Miscellaneous',
    'Bully Mix': 'Miscellaneous',
    'Tosa Inu': 'Miscellaneous',
    'Rhodesian Ridgeback Cross': 'Miscellaneous',
    'Rhodesian Ridgeback X Staffordshire Bull Terrier': 'Miscellaneous',
    'Bull Arab': 'Miscellaneous',
    'Farm Dog': 'Miscellaneous',
    'English Springer Spaniel': 'Miscellaneous',
    'American Masti-Bull': 'Miscellaneous',
    'German Shepherd Mix': 'Shepherd Type'
}